/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Assignment {
  'id' : AssignmentId,
  'title' : string,
  'maxPoints' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'classId' : ClassId,
  'teacherId' : string,
}
export type AssignmentId = bigint;
export interface AssignmentSubmission {
  'studentId' : string,
  'assignmentId' : AssignmentId,
  'submissionDate' : bigint,
  'submissionFile' : ExternalBlob,
}
export type Attachment = { 'file' : ExternalBlob } |
  { 'videoLink' : string };
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'studentId' : string,
  'entryTime' : bigint,
  'classId' : ClassId,
  'sessionId' : SessionId,
  'attendanceId' : AttendanceId,
}
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Class {
  'id' : ClassId,
  'students' : Array<string>,
  'name' : string,
  'teacherId' : string,
  'enrollmentCode' : string,
}
export type ClassId = bigint;
export type ExternalBlob = Uint8Array;
export interface Grade {
  'studentId' : string,
  'gradedBy' : string,
  'score' : bigint,
  'assignmentId' : AssignmentId,
  'comments' : [] | [string],
}
export type MaterialId = bigint;
export interface Message {
  'receiverId' : string,
  'message' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export interface Session {
  'id' : SessionId,
  'title' : string,
  'duration' : bigint,
  'classId' : ClassId,
  'videoLink' : [] | [string],
  'instant' : boolean,
  'dateTime' : bigint,
}
export type SessionId = bigint;
export interface StudyMaterial {
  'id' : MaterialId,
  'name' : string,
  'classId' : ClassId,
  'teacherId' : string,
  'material' : Attachment,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : string,
  'userType' : UserType,
  'classSection' : [] | [string],
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertedGrades' : ActorMethod<
    [],
    Array<[AssignmentId, string, string, bigint, [] | [string]]>
  >,
  'createAssignment' : ActorMethod<
    [ClassId, string, string, bigint, bigint],
    AssignmentId
  >,
  'createClass' : ActorMethod<[string, string], ClassId>,
  'createSession' : ActorMethod<
    [ClassId, string, bigint, bigint, [] | [string], boolean],
    SessionId
  >,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'enrollInClass' : ActorMethod<[string], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAssignmentSubmissions' : ActorMethod<
    [AssignmentId],
    Array<AssignmentSubmission>
  >,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassById' : ActorMethod<[ClassId], Class>,
  'getClasses' : ActorMethod<[], Array<Class>>,
  'getGrades' : ActorMethod<[], Array<Grade>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getSessions' : ActorMethod<[], Array<Session>>,
  'getStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'gradeAssignment' : ActorMethod<
    [AssignmentId, string, bigint, [] | [string]],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'linkChild' : ActorMethod<[string], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markAttendance' : ActorMethod<
    [ClassId, SessionId, string, AttendanceStatus],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitAssignment' : ActorMethod<[AssignmentId, ExternalBlob], undefined>,
  'uploadStudyMaterial' : ActorMethod<
    [ClassId, string, Attachment],
    MaterialId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];