/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssignmentId = IDL.Nat;
export const ClassId = IDL.Nat;
export const SessionId = IDL.Nat;
export const UserType = IDL.Variant({
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'userType' : UserType,
  'classSection' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Text,
});
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'title' : IDL.Text,
  'maxPoints' : IDL.Nat,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'classId' : ClassId,
  'teacherId' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceId = IDL.Nat;
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'entryTime' : IDL.Int,
  'classId' : ClassId,
  'sessionId' : SessionId,
  'attendanceId' : AttendanceId,
});
export const Class = IDL.Record({
  'id' : ClassId,
  'students' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'teacherId' : IDL.Text,
  'enrollmentCode' : IDL.Text,
});
export const Grade = IDL.Record({
  'studentId' : IDL.Text,
  'gradedBy' : IDL.Text,
  'score' : IDL.Nat,
  'assignmentId' : AssignmentId,
  'comments' : IDL.Opt(IDL.Text),
});
export const Session = IDL.Record({
  'id' : SessionId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'classId' : ClassId,
  'videoLink' : IDL.Opt(IDL.Text),
  'instant' : IDL.Bool,
  'dateTime' : IDL.Int,
});
export const MaterialId = IDL.Nat;
export const Attachment = IDL.Variant({
  'file' : ExternalBlob,
  'videoLink' : IDL.Text,
});
export const StudyMaterial = IDL.Record({
  'id' : MaterialId,
  'name' : IDL.Text,
  'classId' : ClassId,
  'teacherId' : IDL.Text,
  'material' : Attachment,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'convertedGrades' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            AssignmentId,
            IDL.Text,
            IDL.Text,
            IDL.Nat,
            IDL.Opt(IDL.Text),
          )
        ),
      ],
      ['query'],
    ),
  'createAssignment' : IDL.Func(
      [ClassId, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [AssignmentId],
      [],
    ),
  'createClass' : IDL.Func([IDL.Text, IDL.Text], [ClassId], []),
  'createSession' : IDL.Func(
      [ClassId, IDL.Text, IDL.Int, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
      [SessionId],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'enrollInClass' : IDL.Func([IDL.Text], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAttendanceRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassById' : IDL.Func([ClassId], [Class], ['query']),
  'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gradeAssignment' : IDL.Func(
      [AssignmentId, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'linkChild' : IDL.Func([IDL.Text], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markAttendance' : IDL.Func(
      [ClassId, SessionId, IDL.Text, AttendanceStatus],
      [],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitAssignment' : IDL.Func([AssignmentId, ExternalBlob], [], []),
  'uploadStudyMaterial' : IDL.Func(
      [ClassId, IDL.Text, Attachment],
      [MaterialId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssignmentId = IDL.Nat;
  const ClassId = IDL.Nat;
  const SessionId = IDL.Nat;
  const UserType = IDL.Variant({
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'userType' : UserType,
    'classSection' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'title' : IDL.Text,
    'maxPoints' : IDL.Nat,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'classId' : ClassId,
    'teacherId' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'entryTime' : IDL.Int,
    'classId' : ClassId,
    'sessionId' : SessionId,
    'attendanceId' : AttendanceId,
  });
  const Class = IDL.Record({
    'id' : ClassId,
    'students' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'teacherId' : IDL.Text,
    'enrollmentCode' : IDL.Text,
  });
  const Grade = IDL.Record({
    'studentId' : IDL.Text,
    'gradedBy' : IDL.Text,
    'score' : IDL.Nat,
    'assignmentId' : AssignmentId,
    'comments' : IDL.Opt(IDL.Text),
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'classId' : ClassId,
    'videoLink' : IDL.Opt(IDL.Text),
    'instant' : IDL.Bool,
    'dateTime' : IDL.Int,
  });
  const MaterialId = IDL.Nat;
  const Attachment = IDL.Variant({
    'file' : ExternalBlob,
    'videoLink' : IDL.Text,
  });
  const StudyMaterial = IDL.Record({
    'id' : MaterialId,
    'name' : IDL.Text,
    'classId' : ClassId,
    'teacherId' : IDL.Text,
    'material' : Attachment,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'convertedGrades' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              AssignmentId,
              IDL.Text,
              IDL.Text,
              IDL.Nat,
              IDL.Opt(IDL.Text),
            )
          ),
        ],
        ['query'],
      ),
    'createAssignment' : IDL.Func(
        [ClassId, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [AssignmentId],
        [],
      ),
    'createClass' : IDL.Func([IDL.Text, IDL.Text], [ClassId], []),
    'createSession' : IDL.Func(
        [ClassId, IDL.Text, IDL.Int, IDL.Nat, IDL.Opt(IDL.Text), IDL.Bool],
        [SessionId],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'enrollInClass' : IDL.Func([IDL.Text], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassById' : IDL.Func([ClassId], [Class], ['query']),
    'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gradeAssignment' : IDL.Func(
        [AssignmentId, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'linkChild' : IDL.Func([IDL.Text], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markAttendance' : IDL.Func(
        [ClassId, SessionId, IDL.Text, AttendanceStatus],
        [],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitAssignment' : IDL.Func([AssignmentId, ExternalBlob], [], []),
    'uploadStudyMaterial' : IDL.Func(
        [ClassId, IDL.Text, Attachment],
        [MaterialId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };